name = "Derpack X: Create"
author = "Alex Ignacio-Gamez"
version = "0.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5aeaae2ac48966257331212687cdfd45552b83ad929fbe918937215a8b3cc1b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
