name = "Project Commonwealth"
author = "Alex Ignacio-Gamez"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97dd4909cb702232fbef180955a0ffbb2f773ee1e42d670db6b2ac7222665ef1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
