name = "Project Commonwealth"
author = "Alex Ignacio-Gamez"
version = "0.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "646403a099a4a44b2c4e0f706da4856c187449f014c96c8a1f04f7a03402e3f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
