#!/usr/bin/env bash
# Extract licensing-SAFE facts from mod jars into a text digest for offline reference.
#
# Captures only functional IDENTIFIERS and tiny structural metadata:
#   - mod id / version / dependency ranges (META-INF/neoforge.mods.toml headers)
#   - block ids   (assets/<ns>/blockstates/*)
#   - item ids    (assets/<ns>/models/item/*)
#   - neoforge biome_modifier contents (ore/spawn/feature injection — small structural json)
#   - c: common tag membership (data/c/tags/** — lists of ids)
#
# Deliberately does NOT copy the mods' creative content: no recipes, loot tables,
# lang strings, models, or textures. Output is IDs/tags only -> safe to commit publicly.
#
# Usage: scripts/extract-mod-data.sh <jars-dir> [out-dir]
set -uo pipefail

JARS="${1:?usage: extract-mod-data.sh <jars-dir> [out-dir]}"
OUT="${2:-tools/mod-data}"
BYMOD="${OUT}/by-mod"
rm -rf "${BYMOD}"; mkdir -p "${BYMOD}"
ORES="${OUT}/INDEX-ores.txt"
BMODS="${OUT}/INDEX-biome-modifiers.txt"
: > "${ORES}"; : > "${BMODS}"

shopt -s nullglob
count=0
for jar in "${JARS}"/*.jar; do
  name="$(basename "${jar}" .jar)"
  {
    echo "# ${name}"
    echo
    echo "## mod metadata (id / version / deps)"
    unzip -p "${jar}" META-INF/neoforge.mods.toml 2>/dev/null \
      | grep -iE '^\s*(modId|version|displayName|license|versionRange)\s*=' | sed 's/^[[:space:]]*//'
    echo
    echo "## blocks"
    unzip -Z1 "${jar}" 2>/dev/null | sed -nE 's#^assets/([^/]+)/blockstates/(.+)\.json$#\1:\2#p' | sort -u
    echo
    echo "## items"
    unzip -Z1 "${jar}" 2>/dev/null | sed -nE 's#^assets/([^/]+)/models/item/(.+)\.json$#\1:\2#p' | sort -u
    echo
    echo "## neoforge biome_modifiers"
    while IFS= read -r p; do
      [ -n "${p}" ] || continue
      printf '%s :: ' "${p##*/biome_modifier/}"
      unzip -p "${jar}" "${p}" 2>/dev/null | tr -d '\n' | tr -s ' '
      echo
    done < <(unzip -Z1 "${jar}" 2>/dev/null | grep -E '/neoforge/biome_modifier/.+\.json$')
    echo
    echo "## c: common tag membership"
    while IFS= read -r p; do
      [ -n "${p}" ] || continue
      printf '%s :: ' "${p#data/c/tags/}"
      unzip -p "${jar}" "${p}" 2>/dev/null | tr -d '\n' | tr -s ' '
      echo
    done < <(unzip -Z1 "${jar}" 2>/dev/null | grep -E '^data/c/tags/.+\.json$')
  } > "${BYMOD}/${name}.txt" 2>/dev/null

  # cross-mod ore census
  unzip -Z1 "${jar}" 2>/dev/null \
    | sed -nE 's#^assets/[^/]+/blockstates/(.*_ore.*)\.json$#'"${name}"': \1#p' >> "${ORES}"
  # cross-mod biome-modifier census (one line each)
  while IFS= read -r p; do
    [ -n "${p}" ] || continue
    printf '%s\t%s\t' "${name}" "${p##*/biome_modifier/}"
    unzip -p "${jar}" "${p}" 2>/dev/null | tr -d '\n' | tr -s ' '
    echo
  done < <(unzip -Z1 "${jar}" 2>/dev/null | grep -E '/neoforge/biome_modifier/.+\.json$') >> "${BMODS}"

  count=$((count + 1))
done

sort -o "${ORES}" "${ORES}"
{
  echo "Mod-data digest — IDs / tags / biome-modifiers only (no recipes/loot/lang/assets)."
  echo "Generated by scripts/extract-mod-data.sh over ${count} jars."
  echo
  echo "  by-mod/<jar>.txt            per-mod blocks, items, biome_modifiers, c: tags, deps"
  echo "  INDEX-ores.txt              every *_ore blockstate across all mods (data-driven census)"
  echo "  INDEX-biome-modifiers.txt   every neoforge biome_modifier across all mods"
  echo
  echo "Note: catches DATA-DRIVEN worldgen only; pair with the in-game EMI ore plugin for"
  echo "ores a mod injects in code (no biome_modifier json)."
} > "${OUT}/README.txt"

echo "Extracted ${count} mods -> ${OUT}"
